### ISSUE TITLE
Does not compile with GCC 11.2.0

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/opensg-1.8#8]
I tried compiling OpenSG on Ubuntu 21.10 with GCC 11.2.0 as part of CosmoScout VR and got the following error many times:

```bash
OSGBase/OSGConnection.h:100:44: error: ISO C++17 does not allow dynamic exception specifications
  100 |     virtual bool wait  (Time timeout = -1) throw (ReadError) = 0;
      |                                            ^~~~~
```

Additionally it gives the following warning, suggesting, that it will be an error in the future aswell:

```bash
OSGReal16.h:465:18: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  465 |     register int e = (x.i >> 23) & 0x000001ff;
      |                  ^
```

It probably becomes inevitable, that we cleanup OpenSG in the near future and throw out all code that we do not need, so we can maintain it easier, when compilers break deprecated features.

**Comment by JonasGilg** [comment]
After a bit of reading we could replace the `throw (...)` with `noexcept(false)`. Maybe a regex would be enough.

**Comment by Schneegans** [comment]
I think in C++ all functions are considered as _potentially throwing_ if nothing is given. So we can simply remove those specifiers. I'll create a PR.
